version: "3.7"
services:
  nginx:  
    image: "nginx:latest"
    container_name: 'nginx-jargon'
    hostname: 'nginx-jargon'
    ports: 
      - "7050:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./node_modules:/mnt/app/node-static
      - ./static:/mnt/app/static
      - ./404.html:/mnt/app/404.html

